[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
command = "npm run build"
publish = ".next"
functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/.netlify/functions/contact"
  to = "/.netlify/functions/contact"
  status = 200

[functions]
node_bundler = "esbuild"
external_node_modules = ["date-fns", "nodemailer"] 